development:
  adapter: mysql2
  encoding: utf8
  database: fruit_example_dev
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: fruit_example_test
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: fruit_example_prod
  username: root
  password: password
  host: 127.0.0.1
  port: 3306